archetypes:
  - namePrefix: nhuppert-kscout-beta
    replicas:
      count: 2
      lifecycle:
        deleteAfter: 42h
        oldestPrimary: 12h
    install:
      helmChart: https://github.com/kscout/monochart.git
stateDir: /home/noah/documents/work/red-hat/auto-cluster/.auto-cluster-state
pullSecretPath: ./pull-secret
