apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auto-cluster.resource-name" . }}-config
  labels:
    component: app
{{ include "auto-cluster.resource-labels" . | indent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "config/*" }}
  {{ $path | base }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
