apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "auto-cluster.resource-name" . }}-data
  labels:
    component: app
{{ include "auto-cluster.resource-labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
