apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auto-cluster.resource-name" . }}-creds
  labels:
    component: app
{{ include "auto-cluster.resource-labels" . | indent 4 }}
type: Opaque
data:
  awsAccessKeyID: {{ .Values.aws.accessKeyID | b64enc }}
  awsSecretAccessKey: {{ .Values.aws.secretAccessKey | b64enc }}
