apiVersion: v1
kind: Service
metadata:
  name: {{ include "auto-cluster.resource-name" . }}
  labels:
    component: app
{{ include "auto-cluster.resource-labels" . | indent 4 }}
spec:
  clusterIP: None
