#global:
  #app:
  #env:

# Stateful container image
image:
  # Container repository
  repo: quay.io/kscout/auto-cluster

  # Container image tag
  tag: latest

# Auto cluster tool configuration
# Will be converted to TOML syntax and placed in config file
# See auto cluster tool docs for config file schema.
autoCluster:
  Cluster:
    NamePrefix: '"nhuppert-kscout"'
    OldestAge: 42
    Namespace: '"kscout"'
  OpenShiftInstall:
    StateStorePath: '"/mnt/data"'
